### ISSUE TITLE
Set width and height of iframe wrapping HTML banner

### ISSUE THREAD

**Issue by rebeckasjostrom** [danschalow/ONE-Adserver-Toolbox#7]
We need the possibility to use a set size for the iframe that the HTML banner is wrapped in as in the initial release of the tool before the iframe was made responsive, this due to issues with detecting banner size once delivered on the website. 

Example of expected result: 

`<iframe src="ad.html?_ADPATH_&_ADCLICK_" scrolling="no" frameborder="0" width="320" height="320"></iframe>`

**Comment by danschalow** [comment]
Will add `input[type=checkbox]` Responsive Iframe to form.

```
<label for="responsive_iframe"><input type="checkbox" id="responsive_iframe" name="responsive_iframe"> Responsive Iframe</label>
```

**Comment by danschalow** [comment]
Added if statement in Class.Creative.php
```php
if($_POST['responsive_iframe']) {
	ob_start();
	include 'php/replacement_files/iframe.php';
	$iframe_php = ob_get_contents();
	ob_end_clean();
}else{
	$iframe_php = '<iframe src="ad.html?_ADPATH_&_ADCLICK_" width="'.$_POST['width'].'" height="'.$_POST['height'].'" scrolling="no" frameborder="0"></iframe>';
}
```
